///////////////////////////////////////////////////////////////////////////////
// ADS_GamepadInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ADS_GamepadServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
