///////////////////////////////////////////////////////////////////////////////
// ADS_GamepadServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ADS_Gamepad = 0x3F000000;
#define SRVNAME_ADS_GAMEPAD "ADS_Gamepad"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ADS_GamepadCGamepad = {0x4a519dae,0xbc7d,0xf0f3,{0xa4,0xcb,0x3f,0x94,0x4e,0x0a,0x3c,0x28}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_GamepadInputs 0
#define ADI_GamepadOutputs 1
#define ADI_GamepadExtOutputs 2
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_GamepadControllerNumber = 0x00000003;
const PTCID PID_GamepadServiceAmsNetId = 0x00000004;
const PTCID PID_GamepadTimeoutCycles = 0x00000005;
const PTCID PID_GamepadStickDeadzonePercent = 0x00000006;
const PTCID PID_GamepadStickCurve = 0x00000007;
const PTCID PID_GamepadTriggerDeadzonePercent = 0x00000008;
const PTCID PID_GamepadTriggerCurve = 0x00000009;
const PTCID PID_GamepadOnlineStickDeadzonePercent = 0x0000000A;
const PTCID PID_GamepadOnlineStickCurve = 0x0000000B;
const PTCID PID_GamepadOnlineTriggerDeadzonePercent = 0x0000000C;
const PTCID PID_GamepadOnlineTriggerCurve = 0x0000000D;
const PTCID PID_GamepadbReadExtended = 0x0000000E;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_0D2B4778_3608_4C16_9CA3_653934376D92_INCLUDED_)
#define _TC_TYPE_0D2B4778_3608_4C16_9CA3_653934376D92_INCLUDED_
typedef struct _ST_GamepadButtons
{
	bool bDPadUp;
	bool bDPadDown;
	bool bDPadLeft;
	bool bDPadRight;
	bool bStart;
	bool bBack;
	bool bLeftThumb;
	bool bRightThumb;
	bool bLeftShoulder;
	bool bRightShoulder;
	bool bA;
	bool bB;
	bool bX;
	bool bY;
	BYTE nReserved1;
	BYTE nReserved2;
} ST_GamepadButtons, *PST_GamepadButtons;
const GUID GUID_ST_GamepadButtons = {0x0D2B4778, 0x3608, 0x4C16, {0x9C, 0xA3, 0x65, 0x39, 0x34, 0x37, 0x6D, 0x92}};
#endif // !defined(_TC_TYPE_0D2B4778_3608_4C16_9CA3_653934376D92_INCLUDED_)

#if !defined(_TC_TYPE_9FA0A70F_30BB_4A3D_96DB_C01BF224E72B_INCLUDED_)
#define _TC_TYPE_9FA0A70F_30BB_4A3D_96DB_C01BF224E72B_INCLUDED_
typedef struct _ST_GamepadServiceInfo
{
	USHORT nContractMajor;
	USHORT nContractMinor;
	USHORT nServiceMajor;
	USHORT nServiceMinor;
	USHORT nServicePatch;
	USHORT nReserved;
	ULONG dwCapabilities;
} ST_GamepadServiceInfo, *PST_GamepadServiceInfo;
const GUID GUID_ST_GamepadServiceInfo = {0x9FA0A70F, 0x30BB, 0x4A3D, {0x96, 0xDB, 0xC0, 0x1B, 0xF2, 0x24, 0xE7, 0x2B}};
#endif // !defined(_TC_TYPE_9FA0A70F_30BB_4A3D_96DB_C01BF224E72B_INCLUDED_)

#if !defined(_TC_TYPE_6687EAFA_79FC_494B_860E_58D797262606_INCLUDED_)
#define _TC_TYPE_6687EAFA_79FC_494B_860E_58D797262606_INCLUDED_
typedef struct _ST_GamepadTouchPoint
{
	bool bActive;
	BYTE nContactId;
	USHORT nX;
	USHORT nY;
} ST_GamepadTouchPoint, *PST_GamepadTouchPoint;
const GUID GUID_ST_GamepadTouchPoint = {0x6687EAFA, 0x79FC, 0x494B, {0x86, 0x0E, 0x58, 0xD7, 0x97, 0x26, 0x26, 0x06}};
#endif // !defined(_TC_TYPE_6687EAFA_79FC_494B_860E_58D797262606_INCLUDED_)

typedef struct _GamepadInputs
{
	float fRumbleLeft;
	float fRumbleRight;
	bool bRumbleEnable;
	unsigned char reserved1[3];
} GamepadInputs, *PGamepadInputs;

typedef struct _GamepadOutputs
{
	bool bConnected;
	BYTE nReserved1;
	BYTE nReserved2;
	BYTE nReserved3;
	ST_GamepadButtons stButtons;
	float fLeftStickX;
	float fLeftStickY;
	float fRightStickX;
	float fRightStickY;
	float fLeftTrigger;
	float fRightTrigger;
	SHORT nButtonsRaw;
	SHORT nStatesRaw;
	ULONG eCommState;
	ULONG nErrorCount;
	ULONG nDataAgeCycles;
	ST_GamepadServiceInfo stServiceInfo;
} GamepadOutputs, *PGamepadOutputs;

typedef struct _GamepadExtOutputs
{
	bool bExtDataPresent;
	bool bPS;
	bool bMute;
	bool bTouchpadClick;
	SHORT nGyroX;
	SHORT nGyroY;
	SHORT nGyroZ;
	SHORT nAccelX;
	SHORT nAccelY;
	SHORT nAccelZ;
	ST_GamepadTouchPoint stTouch0;
	ST_GamepadTouchPoint stTouch1;
	ULONG nSequence;
	ULONG nExtDataAgeCycles;
} GamepadExtOutputs, *PGamepadExtOutputs;

///</AutoGeneratedContent>

// Frozen wire contract v1. The service serves this exact 32 byte block. The
// module keeps it in a private member and publishes only the decoded form.
// The stick field names mirror the service quirks on purpose, do not rename
// or reorder them.
typedef struct _ST_GamepadData
{
	LONG nControllerNumber;
	float fLeftStickY;
	float fLeftStickX;
	float fRightStickY;
	float fRightStickX;
	float fLeftTrigger;
	float fRightTrigger;
	SHORT nButtons;
	SHORT nStates;
} ST_GamepadData, *PST_GamepadData;

// Frozen wire contract v1.3 extended block. The service serves this exact
// 96 byte block at IndexGroup controller number times 0x10000 plus 0x100.
// The module keeps it in a private member and publishes only the decoded
// form. The battery bytes are reserved zeroes until their semantics are
// verified against real charge states.
typedef struct _ST_GamepadExtData
{
	USHORT nExtSize;
	USHORT nExtLayoutVersion;
	USHORT nExtButtons;
	USHORT nExtFlags;
	SHORT nGyroX;
	SHORT nGyroY;
	SHORT nGyroZ;
	SHORT nAccelX;
	SHORT nAccelY;
	SHORT nAccelZ;
	BYTE nTouch0Active;
	BYTE nTouch0ContactId;
	USHORT nTouch0X;
	USHORT nTouch0Y;
	BYTE nTouch1Active;
	BYTE nTouch1ContactId;
	USHORT nTouch1X;
	USHORT nTouch1Y;
	ULONG nSequence;
	BYTE nBatteryPercent;
	BYTE nBatteryFlags;
	USHORT nReserved;
	BYTE aReserved[56];
} ST_GamepadExtData, *PST_GamepadExtData;

// Extended block bit meanings, wire contract v1.3
#define GAMEPAD_EXTFLAG_DATA_PRESENT 0x0001
#define GAMEPAD_EXTBUTTON_PS 0x0001
#define GAMEPAD_EXTBUTTON_MUTE 0x0002
#define GAMEPAD_EXTBUTTON_TOUCHPAD_CLICK 0x0004
#define GAMEPAD_CAPABILITY_EXT_BLOCK 0x00000004

// Wire contract guards. The gamepad block is exactly 32 bytes on the wire,
// the extended block exactly 96, and both layouts are frozen. If one of
// these checks fires the contract was broken by accident. Do not silence
// the checks, fix the layout.
static_assert(sizeof(ST_GamepadData) == 32, "ST_GamepadData must match the 32 byte wire block");
static_assert(sizeof(ST_GamepadButtons) == 16, "ST_GamepadButtons must be 16 bytes to match the data area");
static_assert(sizeof(ST_GamepadServiceInfo) == 16, "ST_GamepadServiceInfo must be 16 bytes");
static_assert(sizeof(GamepadInputs) == 12, "GamepadInputs must be 12 bytes to match the data area");
static_assert(sizeof(GamepadOutputs) == 76, "GamepadOutputs must be 76 bytes to match the data area");
static_assert(sizeof(ST_GamepadExtData) == 96, "ST_GamepadExtData must match the 96 byte wire block");
static_assert(offsetof(_ST_GamepadExtData, nGyroX) == 8, "extended block motion values start at byte 8");
static_assert(offsetof(_ST_GamepadExtData, nTouch0Active) == 20, "extended block touch points start at byte 20");
static_assert(offsetof(_ST_GamepadExtData, nSequence) == 32, "extended block sequence counter sits at byte 32");
static_assert(offsetof(_ST_GamepadExtData, aReserved) == 40, "extended block reserved tail starts at byte 40");
static_assert(sizeof(ST_GamepadTouchPoint) == 6, "ST_GamepadTouchPoint must be 6 bytes to match the data area");
static_assert(sizeof(GamepadExtOutputs) == 36, "GamepadExtOutputs must be 36 bytes to match the data area");

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
