///////////////////////////////////////////////////////////////////////////////
// ADS_GamepadServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ADS_Gamepad = 0x3F000000;
#define SRVNAME_ADS_GAMEPAD "ADS_Gamepad"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ADS_GamepadCGamepad = {0x4a519dae,0xbc7d,0xf0f3,{0xa4,0xcb,0x3f,0x94,0x4e,0x0a,0x3c,0x28}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_GamepadInputs 0
#define ADI_GamepadOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_GamepadControllerNumber = 0x00000003;
const PTCID PID_GamepadServiceAmsNetId = 0x00000004;
const PTCID PID_GamepadTimeoutCycles = 0x00000005;
const PTCID PID_GamepadStickDeadzonePercent = 0x00000006;
const PTCID PID_GamepadStickCurve = 0x00000007;
const PTCID PID_GamepadTriggerDeadzonePercent = 0x00000008;
const PTCID PID_GamepadTriggerCurve = 0x00000009;
const PTCID PID_GamepadOnlineStickDeadzonePercent = 0x0000000A;
const PTCID PID_GamepadOnlineStickCurve = 0x0000000B;
const PTCID PID_GamepadOnlineTriggerDeadzonePercent = 0x0000000C;
const PTCID PID_GamepadOnlineTriggerCurve = 0x0000000D;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_0D2B4778_3608_4C16_9CA3_653934376D92_INCLUDED_)
#define _TC_TYPE_0D2B4778_3608_4C16_9CA3_653934376D92_INCLUDED_
typedef struct _ST_GamepadButtons
{
	bool bDPadUp;
	bool bDPadDown;
	bool bDPadLeft;
	bool bDPadRight;
	bool bStart;
	bool bBack;
	bool bLeftThumb;
	bool bRightThumb;
	bool bLeftShoulder;
	bool bRightShoulder;
	bool bA;
	bool bB;
	bool bX;
	bool bY;
	BYTE nReserved1;
	BYTE nReserved2;
} ST_GamepadButtons, *PST_GamepadButtons;
const GUID GUID_ST_GamepadButtons = {0x0D2B4778, 0x3608, 0x4C16, {0x9C, 0xA3, 0x65, 0x39, 0x34, 0x37, 0x6D, 0x92}};
#endif // !defined(_TC_TYPE_0D2B4778_3608_4C16_9CA3_653934376D92_INCLUDED_)

#if !defined(_TC_TYPE_9FA0A70F_30BB_4A3D_96DB_C01BF224E72B_INCLUDED_)
#define _TC_TYPE_9FA0A70F_30BB_4A3D_96DB_C01BF224E72B_INCLUDED_
typedef struct _ST_GamepadServiceInfo
{
	USHORT nContractMajor;
	USHORT nContractMinor;
	USHORT nServiceMajor;
	USHORT nServiceMinor;
	USHORT nServicePatch;
	USHORT nReserved;
	ULONG dwCapabilities;
} ST_GamepadServiceInfo, *PST_GamepadServiceInfo;
const GUID GUID_ST_GamepadServiceInfo = {0x9FA0A70F, 0x30BB, 0x4A3D, {0x96, 0xDB, 0xC0, 0x1B, 0xF2, 0x24, 0xE7, 0x2B}};
#endif // !defined(_TC_TYPE_9FA0A70F_30BB_4A3D_96DB_C01BF224E72B_INCLUDED_)

typedef struct _GamepadInputs
{
	float fRumbleLeft;
	float fRumbleRight;
	bool bRumbleEnable;
	unsigned char reserved1[3];
} GamepadInputs, *PGamepadInputs;

typedef struct _GamepadOutputs
{
	bool bConnected;
	BYTE nReserved1;
	BYTE nReserved2;
	BYTE nReserved3;
	ST_GamepadButtons stButtons;
	float fLeftStickX;
	float fLeftStickY;
	float fRightStickX;
	float fRightStickY;
	float fLeftTrigger;
	float fRightTrigger;
	SHORT nButtonsRaw;
	SHORT nStatesRaw;
	ULONG eCommState;
	ULONG nErrorCount;
	ULONG nDataAgeCycles;
	ST_GamepadServiceInfo stServiceInfo;
} GamepadOutputs, *PGamepadOutputs;

///</AutoGeneratedContent>

// Frozen wire contract v1. The service serves this exact 32 byte block. The
// module keeps it in a private member and publishes only the decoded form.
// The stick field names mirror the service quirks on purpose, do not rename
// or reorder them.
typedef struct _ST_GamepadData
{
	LONG nControllerNumber;
	float fLeftStickY;
	float fLeftStickX;
	float fRightStickY;
	float fRightStickX;
	float fLeftTrigger;
	float fRightTrigger;
	SHORT nButtons;
	SHORT nStates;
} ST_GamepadData, *PST_GamepadData;

// Wire contract v1 guards. The gamepad block is exactly 32 bytes on the wire
// and the layout is frozen. If one of these checks fires the contract was
// broken by accident. Do not silence the checks, fix the layout.
static_assert(sizeof(ST_GamepadData) == 32, "ST_GamepadData must match the 32 byte wire block");
static_assert(sizeof(ST_GamepadButtons) == 16, "ST_GamepadButtons must be 16 bytes to match the data area");
static_assert(sizeof(ST_GamepadServiceInfo) == 16, "ST_GamepadServiceInfo must be 16 bytes");
static_assert(sizeof(GamepadInputs) == 12, "GamepadInputs must be 12 bytes to match the data area");
static_assert(sizeof(GamepadOutputs) == 76, "GamepadOutputs must be 76 bytes to match the data area");

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
