///////////////////////////////////////////////////////////////////////////////
// ADS_GamepadClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ADS_GamepadClassFactory.h"
#include "ADS_GamepadServices.h"
#include "ADS_GamepadVersion.h"
#include "Gamepad.h"

BEGIN_CLASS_MAP(CADS_GamepadClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_ADS_Gamepad, CID_ADS_GamepadCGamepad, SRVNAME_ADS_GAMEPAD "!CGamepad", CGamepad)
///</AutoGeneratedContent>
END_CLASS_MAP()

CADS_GamepadClassFactory::CADS_GamepadClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ADS_GAMEPAD));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ADS_Gamepad));
#endif //defined(TCDBG_UNIT_VERSION)
}

