///////////////////////////////////////////////////////////////////////////////
// Gamepad.cpp
#include "TcPch.h"
#pragma hdrstop

#include "Gamepad.h"
#include "ADS_GamepadVersion.h"
#include "TcRouterInterfaces.h"

// Frozen wire contract v1 of the gamepad service plus the additive v1.1
// service info block. Do not change these values without a coordinated
// service and library release.
static const AmsPortNo s_GamepadServicePort = 25733;
static const ULONG s_GamepadReadLength = 32;
static const ULONG s_GamepadRumbleOffset = 16;
static const ULONG s_GamepadRumbleLength = 8;
static const ULONG s_GamepadInfoGroup = 0x0000F000;
static const ULONG s_GamepadInfoLength = 32;
static const ULONG s_GamepadTimeoutDefault = 1000;
// Additive extended block of contract v1.3, served per controller at the
// gamepad group plus this offset
static const ULONG s_GamepadExtGroupOffset = 0x100;
static const ULONG s_GamepadExtReadLength = 96;

// Cycles to wait for one candidate address during local target resolution.
// Any answer, success or ADS error, proves the candidate delivers requests
// to the service port, so the probe can be short.
static const ULONG s_GamepadResolveProbeCycles = 100;

// Applied clamp ranges of the tuning parameters
static const float s_GamepadDeadzoneMax = 90.0f;
static const float s_GamepadCurveMin = 0.25f;
static const float s_GamepadCurveMax = 8.0f;

///////////////////////////////////////////////////////////////////////////////
// CGamepad
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CGamepad
BEGIN_INTERFACE_MAP(CGamepad)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CGamepad, VID_ADS_Gamepad, CID_ADS_GamepadCGamepad)
IMPLEMENT_ITCOMOBJECT(CGamepad)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CGamepad)
IMPLEMENT_ITCADI(CGamepad)
IMPLEMENT_ITCWATCHSOURCE(CGamepad)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CGamepad
BEGIN_SETOBJPARA_MAP(CGamepad)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_GamepadControllerNumber, m_ControllerNumber)
	SETOBJPARA_VALUE(PID_GamepadServiceAmsNetId, m_ServiceAmsNetId)
	SETOBJPARA_VALUE(PID_GamepadTimeoutCycles, m_TimeoutCycles)
	SETOBJPARA_VALUE(PID_GamepadStickDeadzonePercent, m_StickDeadzonePercent)
	SETOBJPARA_VALUE(PID_GamepadStickCurve, m_StickCurve)
	SETOBJPARA_VALUE(PID_GamepadTriggerDeadzonePercent, m_TriggerDeadzonePercent)
	SETOBJPARA_VALUE(PID_GamepadTriggerCurve, m_TriggerCurve)
	SETOBJPARA_VALUE(PID_GamepadOnlineStickDeadzonePercent, m_OnlineStickDeadzonePercent)
	SETOBJPARA_VALUE(PID_GamepadOnlineStickCurve, m_OnlineStickCurve)
	SETOBJPARA_VALUE(PID_GamepadOnlineTriggerDeadzonePercent, m_OnlineTriggerDeadzonePercent)
	SETOBJPARA_VALUE(PID_GamepadOnlineTriggerCurve, m_OnlineTriggerCurve)
	SETOBJPARA_VALUE(PID_GamepadbReadExtended, m_bReadExtended)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CGamepad
BEGIN_GETOBJPARA_MAP(CGamepad)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_GamepadControllerNumber, m_ControllerNumber)
	GETOBJPARA_VALUE(PID_GamepadServiceAmsNetId, m_ServiceAmsNetId)
	GETOBJPARA_VALUE(PID_GamepadTimeoutCycles, m_TimeoutCycles)
	GETOBJPARA_VALUE(PID_GamepadStickDeadzonePercent, m_StickDeadzonePercent)
	GETOBJPARA_VALUE(PID_GamepadStickCurve, m_StickCurve)
	GETOBJPARA_VALUE(PID_GamepadTriggerDeadzonePercent, m_TriggerDeadzonePercent)
	GETOBJPARA_VALUE(PID_GamepadTriggerCurve, m_TriggerCurve)
	GETOBJPARA_VALUE(PID_GamepadOnlineStickDeadzonePercent, m_OnlineStickDeadzonePercent)
	GETOBJPARA_VALUE(PID_GamepadOnlineStickCurve, m_OnlineStickCurve)
	GETOBJPARA_VALUE(PID_GamepadOnlineTriggerDeadzonePercent, m_OnlineTriggerDeadzonePercent)
	GETOBJPARA_VALUE(PID_GamepadOnlineTriggerCurve, m_OnlineTriggerCurve)
	GETOBJPARA_VALUE(PID_GamepadbReadExtended, m_bReadExtended)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CGamepad
BEGIN_OBJPARAWATCH_MAP(CGamepad)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CGamepad
BEGIN_OBJDATAAREA_MAP(CGamepad)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_GamepadInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_GamepadOutputs, m_Outputs)
	OBJDATAAREA_VALUE(ADI_GamepadExtOutputs, m_ExtOutputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CGamepad::CGamepad()
	: m_Trace(m_TraceLevelMax, m_spSrv)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_ControllerNumber = 0;
	memset(&m_ServiceAmsNetId, 0, sizeof(m_ServiceAmsNetId));
	m_TimeoutCycles = 0;
	m_StickDeadzonePercent = 0;
	m_StickCurve = 0;
	m_TriggerDeadzonePercent = 0;
	m_TriggerCurve = 0;
	m_OnlineStickDeadzonePercent = 0;
	m_OnlineStickCurve = 0;
	m_OnlineTriggerDeadzonePercent = 0;
	m_OnlineTriggerCurve = 0;
	m_bReadExtended = FALSE;
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
	memset(&m_ExtOutputs, 0, sizeof(m_ExtOutputs));
///</AutoGeneratedContent>

	// Fallback tuning defaults. Init data overwrites these when the instance
	// delivers parameter values, but a parameter that arrives without init
	// data, for example one flagged as an online parameter, must not start
	// at zero. These values match the TMC defaults
	m_StickDeadzonePercent = 10.0f;
	m_StickCurve = 1.0f;
	m_TriggerDeadzonePercent = 0.0f;
	m_TriggerCurve = 1.0f;

	m_AdsStamp = 0;
	m_AdsCnt = 0;
	m_Phase = Phase_Idle;
	m_bStampCreated = false;
	m_bRequestInFlight = false;
	m_bWriteInFlight = false;
	m_bForceReadNext = false;
	m_CyclesInFlight = 0;
	m_RumbleTx[0] = 0.0f;
	m_RumbleTx[1] = 0.0f;
	m_RumbleSent[0] = 0.0f;
	m_RumbleSent[1] = 0.0f;
	m_bRumbleSentValid = false;
	memset(&m_WireData, 0, sizeof(m_WireData));
	memset(&m_ExtWireData, 0, sizeof(m_ExtWireData));
	m_bExtInFlight = false;
	m_bExtReadTurn = false;
	memset(&m_LocalNetId, 0, sizeof(m_LocalNetId));
	m_bLocalNetIdValid = false;
	m_bNeedResolve = false;
	m_bResolved = false;
	memset(m_ResolveCandidates, 0, sizeof(m_ResolveCandidates));
	m_ResolveCandidateCount = 0;
	m_ResolveIndex = 0;
}

///////////////////////////////////////////////////////////////////////////////
CGamepad::~CGamepad()
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CGamepad)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters
// Allocate memory
HRESULT CGamepad::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// wire contract v1 serves controller slots 1 to 4 only
	if (SUCCEEDED(hr) && (m_ControllerNumber < 1 || m_ControllerNumber > 4))
	{
		m_Trace.Log(tlError, FNAMEA_STRV("ControllerNumber %u is invalid, allowed range is 1 to 4", m_ControllerNumber));
		hr = ADS_E_INVALIDPARM;
	}

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CGamepad::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;

	if (SUCCEEDED(hr))
	{
		// fail safe start values, all zero means no gamepad data yet
		memset(&m_Outputs, 0, sizeof(m_Outputs));
		memset(&m_ExtOutputs, 0, sizeof(m_ExtOutputs));
		m_bExtInFlight = false;
		m_bExtReadTurn = false;

		// seed the live tuning values from the init parameters. The init set
		// is stored in the project, the online set is what the shaping uses
		// and what the Parameter (Online) tab adjusts at runtime
		m_OnlineStickDeadzonePercent = m_StickDeadzonePercent;
		m_OnlineStickCurve = m_StickCurve;
		m_OnlineTriggerDeadzonePercent = m_TriggerDeadzonePercent;
		m_OnlineTriggerCurve = m_TriggerCurve;

		QueryLocalNetId();
		ResolveServiceAddr();

		// the task ADS invoker is resolved here when the CyclicCaller
		// interface pointer is wired, otherwise the first cycle retries
		// through the calling task itself
		AcquireAdsInvoker(NULL);

		m_Phase = Phase_Idle;
		m_bRequestInFlight = false;
		m_bWriteInFlight = false;
		m_bForceReadNext = false;
		m_CyclesInFlight = 0;
		m_bRumbleSentValid = false;
	}

	// If the following call succeeds the CycleUpdate method will be called,
	// possibly even before the method has been left
	hr = FAILED(hr) ? hr : AddModuleToCaller();

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		SetObjStateOS();
	}

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CGamepad::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;

	RemoveModuleFromCaller();
	DropRequest();
	ReleaseAdsInvoker();

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CGamepad::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA_STR());

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}


///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CGamepad::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	// age of the gamepad data in task cycles, saturating counter
	if (m_Outputs.nDataAgeCycles < 0xFFFFFFFFUL)
		m_Outputs.nDataAgeCycles++;

	// the extended block has its own age. It climbs forever while extended
	// reads are off or failing, so it never lies fresh
	if (m_ExtOutputs.nExtDataAgeCycles < 0xFFFFFFFFUL)
		m_ExtOutputs.nExtDataAgeCycles++;

	const ULONG timeoutLimit = (m_TimeoutCycles != 0) ? m_TimeoutCycles : s_GamepadTimeoutDefault;

	switch (m_Phase)
	{
	case Phase_Idle:
	{
		if (FAILED(AcquireAdsInvoker(ipTask)))
		{
			FailSafe(GamepadComm_NoTask);
			break;
		}

		if (m_bNeedResolve && !m_bResolved)
		{
			// the configured Net ID means the local system, probe the
			// candidate addresses until one reaches the service
			m_ResolveIndex = 0;
			m_Phase = Phase_Resolve;
			break;
		}

		// one time read of the service info block, contract v1.1. Older
		// services answer with an error, that is fine, the block stays zero
		if (SUCCEEDED(IssueRead(s_GamepadInfoGroup, 0, s_GamepadInfoLength)))
		{
			m_Phase = Phase_InfoRead;
		}
		else
		{
			memset(&m_Outputs.stServiceInfo, 0, sizeof(m_Outputs.stServiceInfo));
			m_Phase = Phase_Run;
		}
		break;
	}

	case Phase_Resolve:
	{
		if (m_bRequestInFlight)
		{
			ULONG adsResult = 0;
			ULONG cbData = 0;
			PVOID pData = NULL;
			HRESULT hr = m_spAdsInvoker->GetAdsCon(m_AdsStamp, &adsResult, &cbData, &pData);
			if (hr == ADS_E_PENDING)
			{
				if (++m_CyclesInFlight >= s_GamepadResolveProbeCycles)
				{
					m_Trace.Log(tlVerbose, FNAMEA_STRV("candidate %u.%u.%u.%u.%u.%u did not answer",
						m_ServiceAddr.netId.b[0], m_ServiceAddr.netId.b[1], m_ServiceAddr.netId.b[2],
						m_ServiceAddr.netId.b[3], m_ServiceAddr.netId.b[4], m_ServiceAddr.netId.b[5]));
					DropRequest();
					AdvanceResolve();
				}
				break;
			}

			if (FAILED(hr))
			{
				// no answer was fetched, the invoker itself failed
				DropRequest();
				AdvanceResolve();
				break;
			}

			// an answer arrived. Success and ADS error both prove that the
			// candidate address delivers requests to the service port, so
			// it is locked in for all further traffic
			m_bResolved = true;
			if (adsResult == 0 && pData != NULL && cbData == s_GamepadInfoLength)
			{
				// the wire block is 32 bytes, the module keeps the first 16,
				// the rest is reserved and zero today
				memcpy(&m_Outputs.stServiceInfo, pData, sizeof(m_Outputs.stServiceInfo));
			}
			else
			{
				memset(&m_Outputs.stServiceInfo, 0, sizeof(m_Outputs.stServiceInfo));
			}
			DropRequest();
			m_Trace.Log(tlInfo, FNAMEA_STRV("service address locked to %u.%u.%u.%u.%u.%u",
				m_ServiceAddr.netId.b[0], m_ServiceAddr.netId.b[1], m_ServiceAddr.netId.b[2],
				m_ServiceAddr.netId.b[3], m_ServiceAddr.netId.b[4], m_ServiceAddr.netId.b[5]));
			m_Phase = Phase_Run;
			break;
		}

		// no probe in flight, send one to the current candidate
		m_ServiceAddr.netId = m_ResolveCandidates[m_ResolveIndex];
		if (FAILED(IssueRead(s_GamepadInfoGroup, 0, s_GamepadInfoLength)))
		{
			AdvanceResolve();
		}
		break;
	}

	case Phase_InfoRead:
	{
		ULONG adsResult = 0;
		ULONG cbData = 0;
		PVOID pData = NULL;
		HRESULT hr = m_spAdsInvoker->GetAdsCon(m_AdsStamp, &adsResult, &cbData, &pData);
		if (hr == ADS_E_PENDING)
		{
			if (++m_CyclesInFlight >= timeoutLimit)
			{
				m_Trace.Log(tlWarning, FNAMEA_STRV("service info read timed out after %u cycles, continuing without it", m_CyclesInFlight));
				DropRequest();
				memset(&m_Outputs.stServiceInfo, 0, sizeof(m_Outputs.stServiceInfo));
				m_Phase = Phase_Run;
			}
			break;
		}

		if (SUCCEEDED(hr))
			hr = MAKE_ADS_HRESULT(adsResult);

		if (SUCCEEDED(hr) && pData != NULL && cbData == s_GamepadInfoLength)
		{
			// the wire block is 32 bytes, the module keeps the first 16,
			// the rest is reserved and zero today
			memcpy(&m_Outputs.stServiceInfo, pData, sizeof(m_Outputs.stServiceInfo));
		}
		else
		{
			memset(&m_Outputs.stServiceInfo, 0, sizeof(m_Outputs.stServiceInfo));
		}
		DropRequest();
		m_Phase = Phase_Run;
		break;
	}

	case Phase_Run:
	{
		if (m_bRequestInFlight)
		{
			ULONG adsResult = 0;
			ULONG cbData = 0;
			PVOID pData = NULL;
			HRESULT hr = m_spAdsInvoker->GetAdsCon(m_AdsStamp, &adsResult, &cbData, &pData);
			if (hr == ADS_E_PENDING)
			{
				if (++m_CyclesInFlight >= timeoutLimit)
				{
					if (m_bWriteInFlight)
						m_bForceReadNext = true;
					// no answer at all proves the service stopped talking,
					// whichever block was asked for. Only an answered
					// extended read error stays isolated; a silent one fails
					// safe like every other timeout, so enabling the extended
					// block never widens the fail safe reaction bound
					DropRequest();
					m_Outputs.nErrorCount++;
					FailSafe(GamepadComm_Timeout);
				}
				break;
			}

			const bool bWasWrite = m_bWriteInFlight;
			const bool bWasExt = m_bExtInFlight;
			if (SUCCEEDED(hr))
				hr = MAKE_ADS_HRESULT(adsResult);

			if (SUCCEEDED(hr) && bWasWrite)
			{
				DropRequest();
				m_RumbleSent[0] = m_RumbleTx[0];
				m_RumbleSent[1] = m_RumbleTx[1];
				m_bRumbleSentValid = true;
			}
			else if (SUCCEEDED(hr) && bWasExt && pData != NULL && cbData == s_GamepadExtReadLength)
			{
				// answer buffer belongs to the invoker, copy before release
				memcpy(&m_ExtWireData, pData, sizeof(m_ExtWireData));
				DropRequest();
				DecodeExtOutputs();
				m_ExtOutputs.nExtDataAgeCycles = 0;
			}
			else if (SUCCEEDED(hr) && !bWasExt && pData != NULL && cbData == s_GamepadReadLength)
			{
				// answer buffer belongs to the invoker, copy before release
				memcpy(&m_WireData, pData, sizeof(m_WireData));
				DropRequest();
				DecodeOutputs();
				m_Outputs.nDataAgeCycles = 0;
				SetCommState(GamepadComm_Ok);
			}
			else if (bWasExt)
			{
				// an extended read error or short answer zeroes only the
				// extended outputs. The gamepad exchange keeps running and
				// keeps owning the comm state
				DropRequest();
				m_Outputs.nErrorCount++;
				ZeroExtOutputs();
			}
			else
			{
				// covers ADS errors and short answers, fail safe either way.
				// a failed rumble write yields one read before the retry so
				// the gamepad data stays alive
				if (bWasWrite)
					m_bForceReadNext = true;
				DropRequest();
				m_Outputs.nErrorCount++;
				FailSafe(GamepadComm_AdsError);
			}
		}

		if (!m_bRequestInFlight)
		{
			const ULONG idxGrp = static_cast<ULONG>(m_ControllerNumber) << 16;

			bool bWrite = false;
			if (m_Inputs.bRumbleEnable && !m_bForceReadNext)
			{
				bWrite = !m_bRumbleSentValid
					|| m_Inputs.fRumbleLeft != m_RumbleSent[0]
					|| m_Inputs.fRumbleRight != m_RumbleSent[1];
			}
			// a forced slot always carries the gamepad read, so live data
			// returns after one round trip even when the extended turn is
			// pending; the extended read simply waits one more cycle
			const bool bForcedRead = m_bForceReadNext;
			m_bForceReadNext = false;

			HRESULT hr;
			bool bExtRead = false;
			if (bWrite)
			{
				// payload must stay stable while the write is in flight
				m_RumbleTx[0] = m_Inputs.fRumbleLeft;
				m_RumbleTx[1] = m_Inputs.fRumbleRight;
				hr = IssueWrite(idxGrp, s_GamepadRumbleOffset, s_GamepadRumbleLength, m_RumbleTx);
			}
			else if (!bForcedRead && ExtReadEnabled() && m_bExtReadTurn)
			{
				// reads alternate between the gamepad block and the extended
				// block, so each runs at half the task rate
				bExtRead = true;
				m_bExtReadTurn = false;
				hr = IssueRead(idxGrp + s_GamepadExtGroupOffset, 0, s_GamepadExtReadLength);
			}
			else
			{
				m_bExtReadTurn = ExtReadEnabled();
				hr = IssueRead(idxGrp, 0, s_GamepadReadLength);
			}

			if (FAILED(hr))
			{
				m_Outputs.nErrorCount++;
				if (bExtRead)
					ZeroExtOutputs();
				else
					FailSafe(GamepadComm_AdsError);
			}
			else if (bExtRead)
			{
				m_bExtInFlight = true;
			}
		}
		break;
	}

	default:
		m_Phase = Phase_Idle;
		break;
	}

	return S_OK;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
// Register the module for cyclic execution with the task named by the
// CyclicCaller interface pointer. Without a valid task OID the transition
// to OP fails on purpose, an unwired module would never be called
HRESULT CGamepad::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID;
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CGamepad::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}

///////////////////////////////////////////////////////////////////////////////
// Ask the router object for the local AMS Net ID. On this platform ADS
// requests from the task port to the loopback Net ID are not answered, so
// the real local Net ID is the best candidate for local resolution.
void CGamepad::QueryLocalNetId()
{
	m_bLocalNetIdValid = false;
	memset(&m_LocalNetId, 0, sizeof(m_LocalNetId));

	ITComRouterPtr spRouter;
	HRESULT hr = m_spSrv->TcQueryObjectInterface(OID_TCROUTER_CTRL, spRouter.GetIID(), reinterpret_cast<PPVOID>(&spRouter));
	if (FAILED(hr) || !spRouter)
	{
		m_Trace.Log(tlVerbose, FNAMEA_STRV("router object not available, hr=0x%08x", hr));
		return;
	}

	AmsNetId netId;
	memset(&netId, 0, sizeof(netId));
	spRouter->GetLocalNetId(netId);

	bool bAllZero = true;
	for (int i = 0; i < 6; i++)
	{
		if (netId.b[i] != 0)
			bAllZero = false;
	}
	if (bAllZero || memcmp(&netId, &AMSNETID_LOOPBACK, sizeof(netId)) == 0)
	{
		m_Trace.Log(tlVerbose, FNAMEA_STRN("router reported no usable local Net ID"));
		return;
	}

	m_LocalNetId = netId;
	m_bLocalNetIdValid = true;
	m_Trace.Log(tlInfo, FNAMEA_STRV("router reports local Net ID %u.%u.%u.%u.%u.%u",
		netId.b[0], netId.b[1], netId.b[2], netId.b[3], netId.b[4], netId.b[5]));
}

///////////////////////////////////////////////////////////////////////////////
// Build the target address from the ServiceAmsNetId parameter. All zeros
// and the loopback Net ID both mean the local system. In that case the
// state machine probes candidate addresses until one answers, because the
// loopback Net ID is not reliably routed from the task port.
void CGamepad::ResolveServiceAddr()
{
	m_ServiceAddr.port = s_GamepadServicePort;

	bool bAllZero = true;
	for (int i = 0; i < 6; i++)
	{
		if (m_ServiceAmsNetId.b[i] != 0)
			bAllZero = false;
	}
	const bool bLoopback = memcmp(&m_ServiceAmsNetId, &AMSNETID_LOOPBACK, sizeof(m_ServiceAmsNetId)) == 0;

	m_bNeedResolve = bAllZero || bLoopback;
	m_bResolved = false;
	m_ResolveCandidateCount = 0;
	m_ResolveIndex = 0;

	if (!m_bNeedResolve)
	{
		// a real Net ID is configured, use it directly
		m_ServiceAddr.netId = m_ServiceAmsNetId;
		return;
	}

	// candidate order: the router supplied local Net ID first, then the
	// all zero address, then loopback. The first candidate that answers
	// the info block read is locked in for all further traffic.
	if (m_bLocalNetIdValid)
		m_ResolveCandidates[m_ResolveCandidateCount++] = m_LocalNetId;
	AmsNetId zeroNetId;
	memset(&zeroNetId, 0, sizeof(zeroNetId));
	m_ResolveCandidates[m_ResolveCandidateCount++] = zeroNetId;
	m_ResolveCandidates[m_ResolveCandidateCount++] = AMSNETID_LOOPBACK;
	m_ServiceAddr.netId = m_ResolveCandidates[0];
}

///////////////////////////////////////////////////////////////////////////////
// Move on to the next candidate address. When the whole list failed the
// timeout is published once and probing starts over, the module never
// gives up on finding the service.
void CGamepad::AdvanceResolve()
{
	m_ResolveIndex++;
	if (m_ResolveIndex >= m_ResolveCandidateCount)
	{
		m_ResolveIndex = 0;
		m_Outputs.nErrorCount++;
		FailSafe(GamepadComm_Timeout);
	}
}

///////////////////////////////////////////////////////////////////////////////
// Resolve the ADS invoker of the task that drives this module and create
// the request stamp. Preferred source is the CyclicCaller interface pointer,
// the calling task itself is the fallback.
HRESULT CGamepad::AcquireAdsInvoker(ITcTask* ipTask)
{
	if (m_spAdsInvoker && m_bStampCreated)
		return S_OK;

	if (!m_spAdsInvoker && m_spCyclicCaller.HasOID())
	{
		m_spSrv->TcQueryObjectInterface(m_spCyclicCaller.GetOID(), m_spAdsInvoker.GetIID(), reinterpret_cast<PPVOID>(&m_spAdsInvoker));
	}
	if (!m_spAdsInvoker && ipTask != NULL)
	{
		ipTask->TcQueryInterface(m_spAdsInvoker.GetIID(), reinterpret_cast<PPVOID>(&m_spAdsInvoker));
	}
	if (!m_spAdsInvoker)
		return ADS_E_INVALIDOBJID;

	HRESULT hr = m_spAdsInvoker->CreateStamp(m_AdsStamp);
	if (FAILED(hr))
	{
		m_Trace.Log(tlError, FNAMEA_STRV("CreateStamp failed, hr=0x%08x", hr));
		m_spAdsInvoker = NULL;
		return hr;
	}
	m_bStampCreated = true;
	return S_OK;
}

///////////////////////////////////////////////////////////////////////////////
void CGamepad::ReleaseAdsInvoker()
{
	m_spAdsInvoker = NULL;
	m_bStampCreated = false;
	m_Phase = Phase_Idle;
}

///////////////////////////////////////////////////////////////////////////////
// Start an ADS read on the task port. The invoker owns the answer buffer,
// it is fetched and copied on completion.
HRESULT CGamepad::IssueRead(ULONG idxGrp, ULONG idxOffs, ULONG cbLength)
{
	if (!m_spAdsInvoker || !m_bStampCreated || m_bRequestInFlight)
		return ADS_E_INVALIDSTATE;

	m_AdsCnt++;
	HRESULT hr = m_spAdsInvoker->ReadReqInv(m_AdsStamp, m_AdsCnt, m_ServiceAddr, idxGrp, idxOffs, cbLength, NULL);
	if (FAILED(hr))
		return hr;

	m_bRequestInFlight = true;
	m_bWriteInFlight = false;
	m_CyclesInFlight = 0;
	return S_OK;
}

///////////////////////////////////////////////////////////////////////////////
// Start an ADS write on the task port. pData must stay valid until the
// answer arrives, callers pass a member buffer.
HRESULT CGamepad::IssueWrite(ULONG idxGrp, ULONG idxOffs, ULONG cbLength, PVOID pData)
{
	if (!m_spAdsInvoker || !m_bStampCreated || m_bRequestInFlight)
		return ADS_E_INVALIDSTATE;

	m_AdsCnt++;
	HRESULT hr = m_spAdsInvoker->WriteReqInv(m_AdsStamp, m_AdsCnt, m_ServiceAddr, idxGrp, idxOffs, cbLength, pData);
	if (FAILED(hr))
		return hr;

	m_bRequestInFlight = true;
	m_bWriteInFlight = true;
	m_CyclesInFlight = 0;
	return S_OK;
}

///////////////////////////////////////////////////////////////////////////////
// Remove the pending request context from the invoker and clear the in
// flight bookkeeping. Safe to call without a pending request.
void CGamepad::DropRequest()
{
	if (m_bRequestInFlight && m_spAdsInvoker)
		m_spAdsInvoker->RemoveAdsCon(m_AdsStamp);
	m_bRequestInFlight = false;
	m_bWriteInFlight = false;
	m_bExtInFlight = false;
	m_CyclesInFlight = 0;
}

///////////////////////////////////////////////////////////////////////////////
void CGamepad::SetCommState(ULONG state)
{
	if (m_Outputs.eCommState != state)
	{
		m_Trace.Log(tlInfo, FNAMEA_STRV("comm state changed from %u to %u", m_Outputs.eCommState, state));
		m_Outputs.eCommState = state;
	}
}

///////////////////////////////////////////////////////////////////////////////
// Zero the decoded gamepad outputs and publish the new comm state. The
// consumer sees a disconnected gamepad with centered sticks, so every
// error path funnels through here. The extended outputs are zeroed too,
// stale motion or touch data must not outlive the gamepad data.
void CGamepad::FailSafe(ULONG state)
{
	ZeroDecodedOutputs();
	ZeroExtOutputs();
	SetCommState(state);
}

///////////////////////////////////////////////////////////////////////////////
// Zero everything decoded from the wire block. The diagnostic counters and
// the service info block stay untouched, they describe the communication,
// not the gamepad.
void CGamepad::ZeroDecodedOutputs()
{
	m_Outputs.bConnected = false;
	m_Outputs.nReserved1 = 0;
	m_Outputs.nReserved2 = 0;
	m_Outputs.nReserved3 = 0;
	memset(&m_Outputs.stButtons, 0, sizeof(m_Outputs.stButtons));
	m_Outputs.fLeftStickX = 0.0f;
	m_Outputs.fLeftStickY = 0.0f;
	m_Outputs.fRightStickX = 0.0f;
	m_Outputs.fRightStickY = 0.0f;
	m_Outputs.fLeftTrigger = 0.0f;
	m_Outputs.fRightTrigger = 0.0f;
	m_Outputs.nButtonsRaw = 0;
	m_Outputs.nStatesRaw = 0;
}

///////////////////////////////////////////////////////////////////////////////
// Apply deadzone and curve to one axis or trigger value. The deadzone is
// rescaled away so motion starts smoothly at the deadzone edge, the curve
// is an exponent on the remaining 0 to 1 magnitude. Sign is preserved.
float CGamepad::ShapeValue(float value, float deadzonePercent, float curve)
{
	float deadzone = deadzonePercent;
	if (deadzone < 0.0f)
		deadzone = 0.0f;
	if (deadzone > s_GamepadDeadzoneMax)
		deadzone = s_GamepadDeadzoneMax;

	float exponent = curve;
	if (exponent < s_GamepadCurveMin)
		exponent = s_GamepadCurveMin;
	if (exponent > s_GamepadCurveMax)
		exponent = s_GamepadCurveMax;

	float magnitude = (value < 0.0f) ? -value : value;
	if (magnitude <= deadzone)
		return 0.0f;
	if (magnitude > 100.0f)
		magnitude = 100.0f;

	float unit = (magnitude - deadzone) / (100.0f - deadzone);
	if (exponent != 1.0f)
		unit = powf_(unit, exponent);

	const float shaped = unit * 100.0f;
	return (value < 0.0f) ? -shaped : shaped;
}

///////////////////////////////////////////////////////////////////////////////
// Decode the raw wire block into the output data area. Runs once per
// successful read. Online parameter writes are serialized against
// CycleUpdate by the object lock, so the tuning values are stable here.
void CGamepad::DecodeOutputs()
{
	const SHORT buttons = m_WireData.nButtons;

	m_Outputs.bConnected = (m_WireData.nStates & 0x0001) != 0;
	m_Outputs.stButtons.bDPadUp = (buttons & 0x0001) != 0;
	m_Outputs.stButtons.bDPadDown = (buttons & 0x0002) != 0;
	m_Outputs.stButtons.bDPadLeft = (buttons & 0x0004) != 0;
	m_Outputs.stButtons.bDPadRight = (buttons & 0x0008) != 0;
	m_Outputs.stButtons.bStart = (buttons & 0x0010) != 0;
	m_Outputs.stButtons.bBack = (buttons & 0x0020) != 0;
	m_Outputs.stButtons.bLeftThumb = (buttons & 0x0040) != 0;
	m_Outputs.stButtons.bRightThumb = (buttons & 0x0080) != 0;
	m_Outputs.stButtons.bLeftShoulder = (buttons & 0x0100) != 0;
	m_Outputs.stButtons.bRightShoulder = (buttons & 0x0200) != 0;
	m_Outputs.stButtons.bA = (buttons & 0x1000) != 0;
	m_Outputs.stButtons.bB = (buttons & 0x2000) != 0;
	m_Outputs.stButtons.bX = (buttons & 0x4000) != 0;
	m_Outputs.stButtons.bY = (buttons & 0x8000) != 0;

	m_Outputs.fLeftStickX = ShapeValue(m_WireData.fLeftStickX, m_OnlineStickDeadzonePercent, m_OnlineStickCurve);
	m_Outputs.fLeftStickY = ShapeValue(m_WireData.fLeftStickY, m_OnlineStickDeadzonePercent, m_OnlineStickCurve);
	m_Outputs.fRightStickX = ShapeValue(m_WireData.fRightStickX, m_OnlineStickDeadzonePercent, m_OnlineStickCurve);
	m_Outputs.fRightStickY = ShapeValue(m_WireData.fRightStickY, m_OnlineStickDeadzonePercent, m_OnlineStickCurve);
	m_Outputs.fLeftTrigger = ShapeValue(m_WireData.fLeftTrigger, m_OnlineTriggerDeadzonePercent, m_OnlineTriggerCurve);
	m_Outputs.fRightTrigger = ShapeValue(m_WireData.fRightTrigger, m_OnlineTriggerDeadzonePercent, m_OnlineTriggerCurve);

	m_Outputs.nButtonsRaw = m_WireData.nButtons;
	m_Outputs.nStatesRaw = m_WireData.nStates;
}

///////////////////////////////////////////////////////////////////////////////
// Extended reads run only when the parameter asks for them and the service
// info block announces the extended block in its capabilities. The info
// block is read once at start, so a service upgraded while the module runs
// is picked up at the next restart. If the one time info read failed the
// extended reads stay off, which errs on the quiet side.
bool CGamepad::ExtReadEnabled() const
{
	if (!m_bReadExtended)
		return false;
	return (m_Outputs.stServiceInfo.dwCapabilities & GAMEPAD_CAPABILITY_EXT_BLOCK) != 0;
}

///////////////////////////////////////////////////////////////////////////////
// Decode the raw extended block into its output data area. Runs once per
// successful extended read. The present flag comes from the service, a
// slot without extended data serves all zero with the flag clear.
void CGamepad::DecodeExtOutputs()
{
	m_ExtOutputs.bExtDataPresent = (m_ExtWireData.nExtFlags & GAMEPAD_EXTFLAG_DATA_PRESENT) != 0;
	m_ExtOutputs.bPS = (m_ExtWireData.nExtButtons & GAMEPAD_EXTBUTTON_PS) != 0;
	m_ExtOutputs.bMute = (m_ExtWireData.nExtButtons & GAMEPAD_EXTBUTTON_MUTE) != 0;
	m_ExtOutputs.bTouchpadClick = (m_ExtWireData.nExtButtons & GAMEPAD_EXTBUTTON_TOUCHPAD_CLICK) != 0;
	m_ExtOutputs.nGyroX = m_ExtWireData.nGyroX;
	m_ExtOutputs.nGyroY = m_ExtWireData.nGyroY;
	m_ExtOutputs.nGyroZ = m_ExtWireData.nGyroZ;
	m_ExtOutputs.nAccelX = m_ExtWireData.nAccelX;
	m_ExtOutputs.nAccelY = m_ExtWireData.nAccelY;
	m_ExtOutputs.nAccelZ = m_ExtWireData.nAccelZ;
	m_ExtOutputs.stTouch0.bActive = m_ExtWireData.nTouch0Active != 0;
	m_ExtOutputs.stTouch0.nContactId = m_ExtWireData.nTouch0ContactId;
	m_ExtOutputs.stTouch0.nX = m_ExtWireData.nTouch0X;
	m_ExtOutputs.stTouch0.nY = m_ExtWireData.nTouch0Y;
	m_ExtOutputs.stTouch1.bActive = m_ExtWireData.nTouch1Active != 0;
	m_ExtOutputs.stTouch1.nContactId = m_ExtWireData.nTouch1ContactId;
	m_ExtOutputs.stTouch1.nX = m_ExtWireData.nTouch1X;
	m_ExtOutputs.stTouch1.nY = m_ExtWireData.nTouch1Y;
	m_ExtOutputs.nSequence = m_ExtWireData.nSequence;
	m_ExtOutputs.bBatteryValid = (m_ExtWireData.nExtFlags & GAMEPAD_EXTFLAG_BATTERY_VALID) != 0;
	m_ExtOutputs.nBatteryPercent = m_ExtWireData.nBatteryPercent;
	m_ExtOutputs.bBatteryCharging = (m_ExtWireData.nBatteryFlags & GAMEPAD_BATTERYFLAG_CHARGING) != 0;
	m_ExtOutputs.bBatteryFull = (m_ExtWireData.nBatteryFlags & GAMEPAD_BATTERYFLAG_FULL) != 0;
}

///////////////////////////////////////////////////////////////////////////////
// Zero everything decoded from the extended block. The age counter stays
// untouched on purpose, it keeps climbing and tells the consumer how old
// the last good extended data is.
void CGamepad::ZeroExtOutputs()
{
	m_ExtOutputs.bExtDataPresent = false;
	m_ExtOutputs.bPS = false;
	m_ExtOutputs.bMute = false;
	m_ExtOutputs.bTouchpadClick = false;
	m_ExtOutputs.nGyroX = 0;
	m_ExtOutputs.nGyroY = 0;
	m_ExtOutputs.nGyroZ = 0;
	m_ExtOutputs.nAccelX = 0;
	m_ExtOutputs.nAccelY = 0;
	m_ExtOutputs.nAccelZ = 0;
	memset(&m_ExtOutputs.stTouch0, 0, sizeof(m_ExtOutputs.stTouch0));
	memset(&m_ExtOutputs.stTouch1, 0, sizeof(m_ExtOutputs.stTouch1));
	m_ExtOutputs.nSequence = 0;
	m_ExtOutputs.nBatteryPercent = 0;
	m_ExtOutputs.bBatteryCharging = false;
	m_ExtOutputs.bBatteryFull = false;
	m_ExtOutputs.bBatteryValid = false;
}
