///////////////////////////////////////////////////////////////////////////////
// Gamepad.h
#pragma once

#include "ADS_GamepadInterfaces.h"

// Values published through the eCommState output
enum EGamepadCommState : ULONG
{
	GamepadComm_Init = 0,     // no gamepad data received yet
	GamepadComm_Ok = 1,       // cyclic exchange with the service is running
	GamepadComm_Timeout = 2,  // no ADS answer within TimeoutCycles
	GamepadComm_AdsError = 3, // the service or the ADS layer returned an error
	GamepadComm_NoTask = 4    // no task ADS invoker available, module is idle
};

class CGamepad
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CGamepad();
	virtual	~CGamepad();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	USHORT m_ControllerNumber;
	AmsNetId m_ServiceAmsNetId;
	USHORT m_TimeoutCycles;
	float m_StickDeadzonePercent;
	float m_StickCurve;
	float m_TriggerDeadzonePercent;
	float m_TriggerCurve;
	float m_OnlineStickDeadzonePercent;
	float m_OnlineStickCurve;
	float m_OnlineTriggerDeadzonePercent;
	float m_OnlineTriggerCurve;
	bool m_bReadExtended;
	GamepadInputs m_Inputs;
	GamepadOutputs m_Outputs;
	GamepadExtOutputs m_ExtOutputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// Phases of the internal request state machine
	enum EAdsPhase : ULONG
	{
		Phase_Idle = 0,     // no ADS invoker resolved, nothing in flight
		Phase_Resolve,      // probing candidate addresses for the local service
		Phase_InfoRead,     // one time read of the service info block
		Phase_Run           // cyclic gamepad read and rumble write
	};

	// ADS client plumbing, at most one request in flight
	void QueryLocalNetId();
	void ResolveServiceAddr();
	void AdvanceResolve();
	HRESULT AcquireAdsInvoker(ITcTask* ipTask);
	void ReleaseAdsInvoker();
	HRESULT IssueRead(ULONG idxGrp, ULONG idxOffs, ULONG cbLength);
	HRESULT IssueWrite(ULONG idxGrp, ULONG idxOffs, ULONG cbLength, PVOID pData);
	void DropRequest();
	void SetCommState(ULONG state);
	void FailSafe(ULONG state);

	// decoding of the raw wire block into the output data area
	void DecodeOutputs();
	void ZeroDecodedOutputs();
	static float ShapeValue(float value, float deadzonePercent, float curve);

	// extended block of wire contract v1.3, read only when bReadExtended is
	// set and the service capabilities announce the block
	bool ExtReadEnabled() const;
	void DecodeExtOutputs();
	void ZeroExtOutputs();

	ITcAdsInvokerPtr m_spAdsInvoker;
	AmsAddr m_ServiceAddr;
	TcAdsInvokerStamp m_AdsStamp;
	TcAdsInvokerCnt m_AdsCnt;
	ULONG m_Phase;
	bool m_bStampCreated;
	bool m_bRequestInFlight;
	bool m_bWriteInFlight;    // the request in flight is the rumble write
	bool m_bForceReadNext;    // after a failed write one read runs first
	ULONG m_CyclesInFlight;
	float m_RumbleTx[2];      // payload kept stable while the write is in flight
	float m_RumbleSent[2];    // last values confirmed by the service
	bool m_bRumbleSentValid;

	ST_GamepadData m_WireData; // last raw wire block, decoded into m_Outputs
	ST_GamepadExtData m_ExtWireData; // last raw extended block, decoded into m_ExtOutputs
	bool m_bExtInFlight;      // the request in flight is the extended read
	bool m_bExtReadTurn;      // the next read is the extended one

	// local target resolution, used when the configured Net ID means the
	// local system (all zeros or loopback)
	AmsNetId m_LocalNetId;         // local Net ID reported by the router
	bool m_bLocalNetIdValid;
	bool m_bNeedResolve;           // configured Net ID means the local system
	bool m_bResolved;              // a candidate answered and is locked in
	AmsNetId m_ResolveCandidates[3];
	ULONG m_ResolveCandidateCount;
	ULONG m_ResolveIndex;
};
