<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MAIN" Id="{6229c1e7-7648-4318-a777-35026c64ff5c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// Gamepad from the AdsGamepad library. An empty NetID means the local machine
	XBOX_Elite		: FB_Gamepad_Controller('', 1);
	XBOX_Adaptive	: FB_Gamepad_Controller('', 2);
	Dual_Sense		: FB_Gamepad_Controller('', 3);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[XBOX_Elite.Cycle();
XBOX_Adaptive.Cycle();
Dual_Sense.Cycle();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>